apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: prettypipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prettypipelinesjavascriptdocker 
    spec:
      containers:
        - name: prettypipelinesjavascriptdocker 
          image: spacr01.azurecr.io/prettypipelinesjavascriptdocker
          ports:
          - containerPort: 8080